# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(523, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 110, 49, 16))
        self.label.setObjectName("label")
        self.cmbGenero = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cmbGenero.setGeometry(QtCore.QRect(50, 150, 371, 22))
        self.cmbGenero.setObjectName("cmbGenero")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(60, 190, 49, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(60, 320, 49, 16))
        self.label_3.setObjectName("label_3")
        self.btnGenerar = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnGenerar.setGeometry(QtCore.QRect(60, 270, 231, 24))
        self.btnGenerar.setObjectName("btnGenerar")
        self.cmbCuil = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cmbCuil.setGeometry(QtCore.QRect(60, 360, 371, 21))
        self.cmbCuil.setObjectName("cmbCuil")
        self.cmbDni = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.cmbDni.setGeometry(QtCore.QRect(60, 210, 361, 21))
        self.cmbDni.setObjectName("cmbDni")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 20, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 523, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtGui.QAction(parent=MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "GENERO"))
        self.label_2.setText(_translate("MainWindow", "DNI"))
        self.label_3.setText(_translate("MainWindow", "CUIL"))
        self.btnGenerar.setText(_translate("MainWindow", "Generar"))
        self.label_4.setText(_translate("MainWindow", "GENERAR CUIL"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExport.setText(_translate("MainWindow", "Export"))
